[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y openjdk-17-jdk",
    "update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java"
]

[phases.install]
cmds = ["./mvnw clean package -DskipTests"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -jar target/*.jar"