[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.install]
cmds = ["chmod +x mvnw", "./mvnw dependency:go-offline"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -jar target/*.jar"
