[providers]
java = "17"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget"
]

[phases.install]
cmds = ["./mvnw dependency:resolve"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -jar target/*.jar"